# ===== ?????? ?? ?? =====
spring:
  application:
    name: auth-service

  # ===== MongoDB ?? =====
  data:
    mongodb:
      uri: mongodb://localhost:27017/board-system
      database: board-system

  # ===== Jackson ?? =====
  jackson:
    default-property-inclusion: non_null

  # ===== ??? ?? (Gmail) =====
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:testEmail@gmail.com}
    password: ${MAIL_PASSWORD:testAppPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    # ??? ??? ??
    default-encoding: UTF-8

# ===== ?? ?? =====
server:
  port: 9081

# ===== JWT ?? =====
jwt:
  secret: mySecretKeyForBoardSystemMSAProject2025
  expiration: 86400000  # 24?? (???)

# ===== ?? ?? =====
logging:
  level:
    org.springframework: INFO
    study: DEBUG

# ===== ??? ?? ?? =====
auth:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}

# ===== ??? ?? ?? =====
email:
  verification:
    code-length: 6              # ?? ?? ??
    expiration-minutes: 30      # ?? ?? (?)
    from-name: Board System     # ??? ??
    from-email: ${MAIL_USERNAME:noreply@boardsystem.com}
